/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RicordiRouteImport } from './routes/ricordi'
import { Route as RicetteRouteImport } from './routes/ricette'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as ProfiloRouteImport } from './routes/profilo'
import { Route as PremiRouteImport } from './routes/premi'
import { Route as NemiciRouteImport } from './routes/nemici'
import { Route as NavicellaRouteImport } from './routes/navicella'
import { Route as MissioniRouteImport } from './routes/missioni'
import { Route as MercatoRouteImport } from './routes/mercato'
import { Route as MappaRouteImport } from './routes/mappa'
import { Route as LabRouteImport } from './routes/lab'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BaseRouteImport } from './routes/base'
import { Route as ArchivioRouteImport } from './routes/archivio'
import { Route as AgentiRouteImport } from './routes/agenti'
import { Route as IndexRouteImport } from './routes/index'

const RicordiRoute = RicordiRouteImport.update({
  id: '/ricordi',
  path: '/ricordi',
  getParentRoute: () => rootRouteImport,
} as any)
const RicetteRoute = RicetteRouteImport.update({
  id: '/ricette',
  path: '/ricette',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfiloRoute = ProfiloRouteImport.update({
  id: '/profilo',
  path: '/profilo',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiRoute = PremiRouteImport.update({
  id: '/premi',
  path: '/premi',
  getParentRoute: () => rootRouteImport,
} as any)
const NemiciRoute = NemiciRouteImport.update({
  id: '/nemici',
  path: '/nemici',
  getParentRoute: () => rootRouteImport,
} as any)
const NavicellaRoute = NavicellaRouteImport.update({
  id: '/navicella',
  path: '/navicella',
  getParentRoute: () => rootRouteImport,
} as any)
const MissioniRoute = MissioniRouteImport.update({
  id: '/missioni',
  path: '/missioni',
  getParentRoute: () => rootRouteImport,
} as any)
const MercatoRoute = MercatoRouteImport.update({
  id: '/mercato',
  path: '/mercato',
  getParentRoute: () => rootRouteImport,
} as any)
const MappaRoute = MappaRouteImport.update({
  id: '/mappa',
  path: '/mappa',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseRoute = BaseRouteImport.update({
  id: '/base',
  path: '/base',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivioRoute = ArchivioRouteImport.update({
  id: '/archivio',
  path: '/archivio',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentiRoute = AgentiRouteImport.update({
  id: '/agenti',
  path: '/agenti',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenti': typeof AgentiRoute
  '/archivio': typeof ArchivioRoute
  '/base': typeof BaseRoute
  '/chat': typeof ChatRoute
  '/inventario': typeof InventarioRoute
  '/lab': typeof LabRoute
  '/mappa': typeof MappaRoute
  '/mercato': typeof MercatoRoute
  '/missioni': typeof MissioniRoute
  '/navicella': typeof NavicellaRoute
  '/nemici': typeof NemiciRoute
  '/premi': typeof PremiRoute
  '/profilo': typeof ProfiloRoute
  '/radar': typeof RadarRoute
  '/ricette': typeof RicetteRoute
  '/ricordi': typeof RicordiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenti': typeof AgentiRoute
  '/archivio': typeof ArchivioRoute
  '/base': typeof BaseRoute
  '/chat': typeof ChatRoute
  '/inventario': typeof InventarioRoute
  '/lab': typeof LabRoute
  '/mappa': typeof MappaRoute
  '/mercato': typeof MercatoRoute
  '/missioni': typeof MissioniRoute
  '/navicella': typeof NavicellaRoute
  '/nemici': typeof NemiciRoute
  '/premi': typeof PremiRoute
  '/profilo': typeof ProfiloRoute
  '/radar': typeof RadarRoute
  '/ricette': typeof RicetteRoute
  '/ricordi': typeof RicordiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenti': typeof AgentiRoute
  '/archivio': typeof ArchivioRoute
  '/base': typeof BaseRoute
  '/chat': typeof ChatRoute
  '/inventario': typeof InventarioRoute
  '/lab': typeof LabRoute
  '/mappa': typeof MappaRoute
  '/mercato': typeof MercatoRoute
  '/missioni': typeof MissioniRoute
  '/navicella': typeof NavicellaRoute
  '/nemici': typeof NemiciRoute
  '/premi': typeof PremiRoute
  '/profilo': typeof ProfiloRoute
  '/radar': typeof RadarRoute
  '/ricette': typeof RicetteRoute
  '/ricordi': typeof RicordiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenti'
    | '/archivio'
    | '/base'
    | '/chat'
    | '/inventario'
    | '/lab'
    | '/mappa'
    | '/mercato'
    | '/missioni'
    | '/navicella'
    | '/nemici'
    | '/premi'
    | '/profilo'
    | '/radar'
    | '/ricette'
    | '/ricordi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenti'
    | '/archivio'
    | '/base'
    | '/chat'
    | '/inventario'
    | '/lab'
    | '/mappa'
    | '/mercato'
    | '/missioni'
    | '/navicella'
    | '/nemici'
    | '/premi'
    | '/profilo'
    | '/radar'
    | '/ricette'
    | '/ricordi'
  id:
    | '__root__'
    | '/'
    | '/agenti'
    | '/archivio'
    | '/base'
    | '/chat'
    | '/inventario'
    | '/lab'
    | '/mappa'
    | '/mercato'
    | '/missioni'
    | '/navicella'
    | '/nemici'
    | '/premi'
    | '/profilo'
    | '/radar'
    | '/ricette'
    | '/ricordi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentiRoute: typeof AgentiRoute
  ArchivioRoute: typeof ArchivioRoute
  BaseRoute: typeof BaseRoute
  ChatRoute: typeof ChatRoute
  InventarioRoute: typeof InventarioRoute
  LabRoute: typeof LabRoute
  MappaRoute: typeof MappaRoute
  MercatoRoute: typeof MercatoRoute
  MissioniRoute: typeof MissioniRoute
  NavicellaRoute: typeof NavicellaRoute
  NemiciRoute: typeof NemiciRoute
  PremiRoute: typeof PremiRoute
  ProfiloRoute: typeof ProfiloRoute
  RadarRoute: typeof RadarRoute
  RicetteRoute: typeof RicetteRoute
  RicordiRoute: typeof RicordiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ricordi': {
      id: '/ricordi'
      path: '/ricordi'
      fullPath: '/ricordi'
      preLoaderRoute: typeof RicordiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ricette': {
      id: '/ricette'
      path: '/ricette'
      fullPath: '/ricette'
      preLoaderRoute: typeof RicetteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profilo': {
      id: '/profilo'
      path: '/profilo'
      fullPath: '/profilo'
      preLoaderRoute: typeof ProfiloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premi': {
      id: '/premi'
      path: '/premi'
      fullPath: '/premi'
      preLoaderRoute: typeof PremiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nemici': {
      id: '/nemici'
      path: '/nemici'
      fullPath: '/nemici'
      preLoaderRoute: typeof NemiciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navicella': {
      id: '/navicella'
      path: '/navicella'
      fullPath: '/navicella'
      preLoaderRoute: typeof NavicellaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missioni': {
      id: '/missioni'
      path: '/missioni'
      fullPath: '/missioni'
      preLoaderRoute: typeof MissioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercato': {
      id: '/mercato'
      path: '/mercato'
      fullPath: '/mercato'
      preLoaderRoute: typeof MercatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mappa': {
      id: '/mappa'
      path: '/mappa'
      fullPath: '/mappa'
      preLoaderRoute: typeof MappaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base': {
      id: '/base'
      path: '/base'
      fullPath: '/base'
      preLoaderRoute: typeof BaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archivio': {
      id: '/archivio'
      path: '/archivio'
      fullPath: '/archivio'
      preLoaderRoute: typeof ArchivioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenti': {
      id: '/agenti'
      path: '/agenti'
      fullPath: '/agenti'
      preLoaderRoute: typeof AgentiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentiRoute: AgentiRoute,
  ArchivioRoute: ArchivioRoute,
  BaseRoute: BaseRoute,
  ChatRoute: ChatRoute,
  InventarioRoute: InventarioRoute,
  LabRoute: LabRoute,
  MappaRoute: MappaRoute,
  MercatoRoute: MercatoRoute,
  MissioniRoute: MissioniRoute,
  NavicellaRoute: NavicellaRoute,
  NemiciRoute: NemiciRoute,
  PremiRoute: PremiRoute,
  ProfiloRoute: ProfiloRoute,
  RadarRoute: RadarRoute,
  RicetteRoute: RicetteRoute,
  RicordiRoute: RicordiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
