/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RicordiRouteImport } from './routes/ricordi'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as ProfiloRouteImport } from './routes/profilo'
import { Route as PremiRouteImport } from './routes/premi'
import { Route as MissioniRouteImport } from './routes/missioni'
import { Route as LabRouteImport } from './routes/lab'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BaseRouteImport } from './routes/base'
import { Route as IndexRouteImport } from './routes/index'

const RicordiRoute = RicordiRouteImport.update({
  id: '/ricordi',
  path: '/ricordi',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfiloRoute = ProfiloRouteImport.update({
  id: '/profilo',
  path: '/profilo',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiRoute = PremiRouteImport.update({
  id: '/premi',
  path: '/premi',
  getParentRoute: () => rootRouteImport,
} as any)
const MissioniRoute = MissioniRouteImport.update({
  id: '/missioni',
  path: '/missioni',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseRoute = BaseRouteImport.update({
  id: '/base',
  path: '/base',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/base': typeof BaseRoute
  '/chat': typeof ChatRoute
  '/lab': typeof LabRoute
  '/missioni': typeof MissioniRoute
  '/premi': typeof PremiRoute
  '/profilo': typeof ProfiloRoute
  '/radar': typeof RadarRoute
  '/ricordi': typeof RicordiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/base': typeof BaseRoute
  '/chat': typeof ChatRoute
  '/lab': typeof LabRoute
  '/missioni': typeof MissioniRoute
  '/premi': typeof PremiRoute
  '/profilo': typeof ProfiloRoute
  '/radar': typeof RadarRoute
  '/ricordi': typeof RicordiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/base': typeof BaseRoute
  '/chat': typeof ChatRoute
  '/lab': typeof LabRoute
  '/missioni': typeof MissioniRoute
  '/premi': typeof PremiRoute
  '/profilo': typeof ProfiloRoute
  '/radar': typeof RadarRoute
  '/ricordi': typeof RicordiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/base'
    | '/chat'
    | '/lab'
    | '/missioni'
    | '/premi'
    | '/profilo'
    | '/radar'
    | '/ricordi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/base'
    | '/chat'
    | '/lab'
    | '/missioni'
    | '/premi'
    | '/profilo'
    | '/radar'
    | '/ricordi'
  id:
    | '__root__'
    | '/'
    | '/base'
    | '/chat'
    | '/lab'
    | '/missioni'
    | '/premi'
    | '/profilo'
    | '/radar'
    | '/ricordi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaseRoute: typeof BaseRoute
  ChatRoute: typeof ChatRoute
  LabRoute: typeof LabRoute
  MissioniRoute: typeof MissioniRoute
  PremiRoute: typeof PremiRoute
  ProfiloRoute: typeof ProfiloRoute
  RadarRoute: typeof RadarRoute
  RicordiRoute: typeof RicordiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ricordi': {
      id: '/ricordi'
      path: '/ricordi'
      fullPath: '/ricordi'
      preLoaderRoute: typeof RicordiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profilo': {
      id: '/profilo'
      path: '/profilo'
      fullPath: '/profilo'
      preLoaderRoute: typeof ProfiloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premi': {
      id: '/premi'
      path: '/premi'
      fullPath: '/premi'
      preLoaderRoute: typeof PremiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missioni': {
      id: '/missioni'
      path: '/missioni'
      fullPath: '/missioni'
      preLoaderRoute: typeof MissioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base': {
      id: '/base'
      path: '/base'
      fullPath: '/base'
      preLoaderRoute: typeof BaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaseRoute: BaseRoute,
  ChatRoute: ChatRoute,
  LabRoute: LabRoute,
  MissioniRoute: MissioniRoute,
  PremiRoute: PremiRoute,
  ProfiloRoute: ProfiloRoute,
  RadarRoute: RadarRoute,
  RicordiRoute: RicordiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
